apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: client # match pods with label "app: client"
  template:
    metadata:
      labels:
        app: client # Create the label that deployment will look for (we are using this on line #9)
    spec:
      containers:
      - name: client-container
        image: gtldhawalgandhi/client
---
apiVersion: v1
kind: Service
metadata:
  name: client-svc
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - protocol: TCP
      name: client
      port: 80
      targetPort: 80
