apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: comments # match pods with label "app: comments"
  template:
    metadata:
      labels:
        app: comments # Create the label that deployment will look for (we are using this on line #9)
    spec:
      containers:
      - name: comments-container
        image: gtldhawalgandhi/comments
---
apiVersion: v1
kind: Service
metadata:
  name: comments-svc
spec:
  selector:
    app: comments
  type: NodePort
  ports:
    - name: comments
      protocol: TCP
      port: 4001
      targetPort: 4001
