apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: query # match pods with label "app: query"
  template:
    metadata:
      labels:
        app: query # Create the label that deployment will look for (we are using this on line #9)
    spec:
      containers:
      - name: query-container
        image: gtldhawalgandhi/query
---
apiVersion: v1
kind: Service
metadata:
  name: query-svc
spec:
  selector:
    app: query
  type: NodePort
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002
